name: grizzly_viz_shape
description: Context-agnostic graphical primitives for visualization
version: 0.0.2-dev
homepage: https://github.com/Grizzly-dart/grizzly_viz_shape
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_viz_scales:
    path: ../grizzly_viz_scales

dev_dependencies:
  test: ^0.12.0
